config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :coins
  
  # Para ver todas as rotas pode usar rails routes no terminal ou
  # acessar no navegador no projeto /rails/info/routes
  # Doc https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  # validates :description, :acronym, :url_image

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Moeda criada com sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Moeda atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Moeda deletada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @coins = Coin.all
    @nome = params[:nome] ? params[:nome] : "Não informado"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_br(data)
      data.strftime('%d/%m/%Y')
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
require 'net/http'
require "json"
# The code is defining a module called `WelcomeHelper` in Ruby. Inside the module, there is a method
# called `btc_price` that takes a parameter `nome_moeda` (which I assume is the name of a
# cryptocurrency).
module WelcomeHelper
    def btc_price(nome_moeda)
      lista = Net::HTTP.new('blockchain.info', 443)
      lista.use_ssl = true
      response = lista.get('/ticker')
      date = JSON.parse(response.body)
      date[nome_moeda]['buy']
    end

    def ambiente_rails
      if Rails.env.development?
        "Desenvolvimento"
      elsif Rails.env.production?
        "Produção"
      else
        "Teste"
      end
    end
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <tr>
    <td><%= coin.description %></td>
    <td><%= coin.acronym %></td>
    <td><%= image_tag coin.url_image, width: 30, heigth: 30 %></td>
    <td style="width: 100%; justfy-contente: space-between; display: flex">
      <span class="m-4">
        <%= link_to "Editar moeda", edit_coin_path(coin), class: "btn btn-primary" %> 
      </span>
      <span class="m-4">
        <%= button_to "Deletar moeda", coin, method: :delete, data: {confirm: "Tem certeza?"}, class: "btn btn-primary mt-1" %>
      </span>
      <span class="m-4">
        <%= link_to "Visualizar Moeda", coin, class: "btn btn-primary" %>
      </span>
    </td>
  </tr>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li class="alert alert-danger"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym, class: "form-control" %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image, class: "form-control" %>
    <%= image_tag coin.url_image ? coin.url_image : "" , size: "30x30", class: "mt-2" %>
  </div>

  <div>
    <%= form.submit "Cadastrar",style: "display: block; width: 100%", class: "btn btn-primary mt-4 p-2" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coins</h1>

<div id="coins">
  <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">sigla</th>
      <th scope="col">imagem</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
    <% @coins.each do |coin| %>
      <%= render coin %>
      
    <% end %>
   </tbody>
  </table>
</div>

<%= link_to "Nova Moeda", new_coin_path, class: "btn btn-primary" %>

app/views/coins/new.html.erb
<h1>Nova Moeda $$$</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Voltar para lista de Moedas", coins_path,class: "btn btn-primary" %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%# <%= render @coin %>

<p>
  <strong>Descrição</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Sigla</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Imagem</strong>
  <%= image_tag @coin.url_image, size: "30x30" %>
</p>

<div>
  <%= link_to "Editar Moeda", edit_coin_path(@coin),class: "btn btn-primary" %>
  <%= link_to "Voltar para lista de moedas", coins_path,class: "btn btn-primary" %>

  <%= button_to "Deletar Moeda", @coin, method: :delete, data: {confirm: "Tem certeza?"}, class: "btn btn-danger mt-4" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/_menu.html.erb
<h1 class="mt-5">Seja Bem-Vindo!</h1>
<p>
    Total de moedas cadastradas: <b><%= @coins.length %></b>
</p>
<p>Hoje é dia: <%= date_br(Date.today) %></p>
<p>Valor do Bitcoin em dolar: <%= btc_price('USD') %></p>
<p>Valor do Bitcoin em real: <%= btc_price('BRL') %></p>

app/views/welcome/index.html.erb
<div class="card p-3 mt-3">
     <%= render "menu" %>
    <p>Rodando no ambiente de: <%= ambiente_rails %></p>
    <p>Nome: <%= @nome.upcase %></p>
    <%= link_to 'Lista de moedas', coins_path, class: 'btn btn-primary p-2' %>
</div>